[package]
name = "{{project-name}}"
version = "0.0.0"
edition = "2021"
rust-version = "{{rust-version}}"
description = "{{project-description}}"
readme = "README.md"
repository = "https://github.com/{{gh-username}}/{{project-name}}"
license = "MIT OR Apache-2.0"
keywords = []
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "{{maintenance-status}}" }

[dependencies]

{% if crate_type == "lib" -%}
[dev-dependencies]
version-sync = "0.9.4"
cargo-readme = "3.2.0"
{%- endif -%}
{% if crate_type == "bin" -%}
[profile.release]
strip = true
{%- endif %}
