version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/template"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/template"
    schedule:
      interval: "daily"
