[settings]
lockfile = true
lockfile_platforms = [
  "linux-x64",
  "linux-arm64",
  "macos-arm64",
  "windows-x64",
  "windows-arm64",
]

[tools]
editorconfig-checker = { version = "4.0.2", lazy = true, lazy_bins = ["editorconfig-checker"] }
"github:cargo-generate/cargo-generate" = { version = "0.25.0", lazy = true, lazy_bins = ["cargo-generate"], platforms.windows-arm64.asset_pattern = "cargo-generate-v{{ version }}-x86_64-pc-windows-msvc.tar.gz" }
jactionlint = { version = "1.8.2", lazy = true }
rumdl = { version = "0.2.78", lazy = true }
shellcheck = { version = "0.11.0", lazy = true }
shfmt = { version = "3.14.1", lazy = true }
tombi = { version = "1.7.3", lazy = true }
typos = { version = "1.51.1", lazy = true }
