[ci]
depends = ["ci:*"]

["ci:lint-workflow"]
depends = ["lint:workflow"]

["ci:lint-spelling"]
depends = ["lint:spelling"]

["ci:lint-markdown"]
depends = [
  "format:markdown --check",
  "lint:markdown",
]

["ci:lint-editorconfig"]
depends = ["lint:editorconfig"]

["ci:lint-shell"]
depends = [
  "format:shell --check",
  "lint:shell",
]

["ci:lint-renovate"]
depends = ["lint:renovate"]
