["format:markdown"]
description = "Format Markdown files"
usage = '''
flag "--check" help="Run rumdl in check mode"
'''
run = '''
rumdl format
  {{- ' --check' if usage.check else '' }}
'''

["lint:markdown"]
description = "Lint Markdown files"
run = "rumdl check"
