#!/bin/bash

set -eux

test_dir="$(dirname "${BASH_SOURCE[0]}")"
cd "${test_dir}"

for crate_type in bin lib; do
    rm -rf "out.${crate_type}"
    mkdir "out.${crate_type}"

    (
        cd "out.${crate_type}"
        git init
        MISE_LOCKED=false cargo generate -v --init \
            --path ../../template \
            "--${crate_type}" \
            --name "rust-template-generated-${crate_type}" \
            --template-values-file ../template_values.toml \
            --allow-commands
        cargo generate-lockfile
        MISE_TRUSTED_CONFIG_PATHS="$PWD" mise lock
        git add .
        git commit -m "Initial commit"
        ../scripts/run_ci "${crate_type}"
    )

    rm -rf "repo.${crate_type}"
    git clone "https://github.com/gifnksm/rust-template-generated-${crate_type}" "repo.${crate_type}"
    ./scripts/update_repo "repo.${crate_type}" "out.${crate_type}"
    (
        cd "repo.${crate_type}"
        git add .
        git commit -m "Sync to latest template"
        ../scripts/run_ci "${crate_type}"
    )
done
