name: Security Audit

on:
  schedule:
    # Runs at 00:00 UTC everyday
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    uses: gifnksm/rust-template/.github/workflows/reusable-audit.yml@main
