name: CD

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  cd:
    uses: gifnksm/rust-template/.github/workflows/reusable-cd.yml@main
    with:
      upload-dist-archive: {% if crate_type == "bin" %}true{% else %}false{% endif %}
    permissions:
      contents: write

  cd-complete:
    needs: cd
    runs-on: ubuntu-latest
    if: {{ "${{ always() }}" }}
    steps:
      - run: |
          if {{ "${{ needs.cd.result == 'success' }}" }}; then
            echo "CD succeeded"
            exit 0
          else
            echo "CD failed"
            exit 1
          fi
