name: CD

on:
  push:
    tags:
      - '[v]?[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
  pull_request:

jobs:
  publish:
    name: Publishing for {{ '${{ matrix.job.target }}' }}
    runs-on: {{ '${{ matrix.job.os }}' }}
    strategy:
      matrix:
        rust: [stable]
        job:
          - os: macos-latest
            target: x86_64-apple-darwin
            binary-suffix: ""
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-suffix: ""
            use-cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-suffix: ".exe"
            use-cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary-suffix: ""
            use-cross: true
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            binary-suffix: ""
            use-cross: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: {{ '${{ matrix.rust }}' }}
          profile: minimal
          override: true

      - name: Sets env vars for push
        shell: bash
        run: |
          echo "RELEASE_REF_NAME={{ '${{ github.ref_name }}' }}" >> $GITHUB_ENV
        if: {{ "${{ github.event_name == 'push' }}" }}

      - name: Sets env vars for pull request
        shell: bash
        run: |
          echo "RELEASE_REF_NAME=pr{{ '${{ github.event.pull_request.number }}' }}" >> $GITHUB_ENV
        if: {{ "${{ github.event_name == 'pull_request' }}" }}

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: {{ '${{ matrix.job.use-cross }}' }}
          toolchain: {{ '${{ matrix.rust }}' }}
          args: --release --target {{ '${{ matrix.job.target }}' }}

      - name: Packaging final binary
        shell: bash
        run: |
          cd target/{{ '${{ matrix.job.target }}' }}/release
          ########## create tar.gz ##########
          RELEASE_NAME={{ project-name }}-${RELEASE_REF_NAME}-{{ '${{ matrix.job.target }}' }}
          BINARY_NAME={{ project-name }}{{ '${{ matrix.job.binary-suffix }}' }}
          tar czvf $RELEASE_NAME.tar.gz $BINARY_NAME
          ########## create sha256 ##########
          if [[ {{ '${{ runner.os }}' }} == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
          fi

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            target/{{ '${{ matrix.job.target }}' }}/release/souko-*.tar.gz
            target/{{ '${{ matrix.job.target }}' }}/release/souko-*.sha256

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/{{ '${{ matrix.job.target }}' }}/release/{{ project-name }}-*.tar.gz
            target/{{ '${{ matrix.job.target }}' }}/release/{{ project-name }}-*.sha256
        env:
          GITHUB_TOKEN: {{ '${{ secrets.GITHUB_TOKEN }}' }}
        if: {{ "${{ startsWith(github.ref, 'refs/tags/') }}" }}
