name: CD

on:
  push:
    tags:
      - "[v]?[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:

jobs:
  publish:
    name: Publishing for {{ "${{ matrix.job.target }}" }}
    runs-on: {{ "${{ matrix.job.os }}" }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            xtask-args: ""
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            xtask-args: --use-cross
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            xtask-args: --use-cross
          - os: macos-latest
            target: x86_64-apple-darwin
            xtask-args: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            xtask-args: ""

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: {{ "${{ matrix.rust }}" }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          key: {{ "${{ matrix.job.target }}" }}
      - name: Install cross
        uses: taiki-e/install-action@cross

      - name: Sets env vars for push
        shell: bash
        run: |
          echo "RELEASE_REF_NAME={{ '${{ github.ref_name }}' }}" >> $GITHUB_ENV
        if: {{ "${{ github.event_name == 'push' }}" }}

      - name: Sets env vars for pull request
        shell: bash
        run: |
          echo "RELEASE_REF_NAME=pr{{ '${{ github.event.pull_request.number }}' }}" >> $GITHUB_ENV
        if: {{ "${{ github.event_name == 'pull_request' }}" }}

      - name: cargo xtask dist
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          toolchain: {{ "${{ matrix.rust }}" }}
          args: dist --tag {{ "${{ env.RELEASE_REF_NAME }}" }} --target {{ "${{ matrix.job.target }}" }} {{ "${{ matrix.job.xtask-args }}" }}

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          path: target/dist/*

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/dist/*
        env:
          GITHUB_TOKEN: {{ "${{ secrets.GITHUB_TOKEN }}" }}
        if: {{ "${{ startsWith(github.ref, 'refs/tags/') }}" }}
