name: CD

env:
  CRATE_TYPE: "{{ crate_type }}"

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:

jobs:
  cd:
    strategy:
      matrix:
        crate_type: [ {{ crate_type }} ]
    uses: gifnksm/rust-template/.github/workflows/reusable-cd.yml@main
    with:
      upload-dist-archive: {{ "${{ matrix.crate_type == 'bin' }}" }}
