name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: gifnksm/rust-template/.github/workflows/reusable-ci.yml@main

  ci-complete:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI completed"
        shell: bash
