name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        job:
          - crate_type: "bin"
          - crate_type: "lib"
    env:
      PROJECT_NAME: rust-template-generated-${{ matrix.job.crate_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: template
          template_values_file: tests/template_values.toml
          other: "--${{ matrix.job.crate_type }}"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.PROJECT_NAME }}
          workspaces: "${{ env.PROJECT_NAME }} -> target"
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-udeps,cargo-rdme
      - run: rustup toolchain add nightly --profile minimal
        shell: bash
      - name: Cargo check
        run: |
          cd "${PROJECT_NAME}"
          ../tests/scripts/run_cargo_tests "${{ matrix.job.crate_type }}"

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          echo "::add-matcher::.github/actionlint-matcher.json"
          ./actionlint -color
        shell: bash
