name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        job:
          - crate_type: "bin"
          - crate_type: "lib"
    env:
      PROJECT_NAME: rust-template-generated-${{ matrix.job.crate_type }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: rustup toolchain add nightly --profile minimal
        shell: bash
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      - run: cargo generate --name "${{ env.PROJECT_NAME }}" --path "template" --template-values-file tests/template_values.toml --${{matrix.job.crate_type}} --allow-commands
        shell: bash
      - name: Cargo check
        env:
          GIT_AUTHOR_NAME: "Dummy Name"
          GIT_AUTHOR_EMAIL: "dummy@example.com"
          GIT_COMMITTER_NAME: "Dummy Name"
          GIT_COMMITTER_EMAIL: "dummy@example.com"
        run: |
          cd "${PROJECT_NAME}"
          git init
          cargo generate-lockfile
          mise lock
          git add .
          git commit -m "Initial commit"
          ../tests/scripts/run_ci "${{ matrix.job.crate_type }}"

  lint-workflow:
    name: Lint (workflow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      - run: mise run ci:lint-workflow
        shell: bash

  lint-spelling:
    name: Lint (spelling)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      - run: mise run ci:lint-spelling
        shell: bash

  lint-markdown:
    name: Lint (markdown)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      - run: mise run ci:lint-markdown
        shell: bash

  lint-editorconfig:
    name: Lint (editorconfig)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      - run: mise run ci:lint-editorconfig
        shell: bash

  lint-shell:
    name: Lint (shell)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      - run: mise run ci:lint-shell
        shell: bash

  lint-renovate:
    name: Lint (renovate)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      - run: mise run ci:lint-renovate
        shell: bash

  ci-complete:
    needs:
      - build
      - lint-workflow
      - lint-spelling
      - lint-markdown
      - lint-editorconfig
      - lint-shell
      - lint-renovate
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: CI complete
        run: |
          if ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}; then
            echo "CI succeeded"
          else
            echo "CI failed"
            exit 1
          fi
        shell: bash
