#!/bin/bash

set -eux

if [[ "$#" -ne 1 ]]; then
  echo "Usage: $0 <crate_type>" >&2
  exit 1
fi

crate_type="$1"
case "${crate_type}" in
bin | lib) ;;
*)
  echo "Invalid crate_type: ${crate_type}" >&2
  exit 1
  ;;
esac

cargo xtask build --exhaustive -- --all-targets
cargo xtask test --exhaustive
cargo xtask lint --exhaustive
if [[ "${crate_type}" == "bin" ]]; then
  cargo xtask dist
fi
