#!/bin/bash

set -eux

if [[ "$#" -ne 1 ]]; then
  echo "Usage: $0 <crate_type>" >&2
  exit 1
fi

crate_type="$1"
case "${crate_type}" in
bin | lib) ;;
*)
  echo "Invalid crate_type: ${crate_type}" >&2
  exit 1
  ;;
esac

just ci
if [[ "${crate_type}" == "bin" ]]; then
  ./scripts/build-dist
fi
